# Generated by Django 2.2.4 on 2019-10-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://thescepticalblogger.com/wp-content/uploads/2019/01/Food-Coming-Soon.png', max_length=500),
        ),
    ]
