# Generated by Django 2.2.4 on 2019-10-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSytCWvTPQR6Q9m-wJG5Xz-nDSSs9cV7n4aVk6oR3hwDB6XbekBdA', max_length=500),
        ),
    ]
